### ISSUE TITLE
New loss weight inversely proportional to the force magnitude

### ISSUE THREAD

**Issue by bapatist** [ACEsuit/mace#141]
Hi all,
during a recent discussion with @gabor1, assessment of % force errors seemed useful for developing possible weighting strategies. Here are the % force errors plotted against force components. MACE model was trained on {water, IrO2, IrO2+water} structures generated by active learning workflows (using GAP). 

<img src="https://github.com/ACEsuit/mace/assets/40303099/8b33f37b-aecc-4149-aca9-18e2f8fdc9f2" alt="Image" width="400" height="300">

**Comment by gabor1** [comment]
The reason I asked for this to be put into an issue is because it shows very clearly how the loss we use makes the absolute error constant, regardless of the size of the force. it would be nice to allow an option where the loss weight is inversely proportional to the force (3 dimensional) norm (with some regularisation), so that the relative force error does not shoot up so much for small forces.

**Comment by ilyes319** [comment]
Present in the new loss called `UniversalLoss` (should change the name)

**Comment by gabor1** [comment]
ForceProportionalLoss ?
